### ISSUE TITLE
Consider using updateConsentState to update consent status

### ISSUE THREAD

**Issue by philpott** [Cytrio/CYTRIO-GTM-Template#1]
https://github.com/Cytrio/CYTRIO-GTM-Template/blob/d95dbe18edc94c22affff5f5af396c0b7407b724/template.tpl#L109

Consider updating consent state using [updateConsentState](https://developers.google.com/tag-platform/tag-manager/templates/api#updateconsentstate) api. This speeds up how fast users see the consent information by jumping the gtag/dataLayer event queue and immediately updating user consent on the page.

**Comment by medhabhatt** [comment]
@philpott thanks for your feedback.  The latest version of the template includes it.
